STILL, LEFT, RIGHT = 'S', 'L', 'R'
ACTIONS = [RIGHT, LEFT, STILL]

REWARD_IMPOSSIBLE = -60
REWARD_STUCK = -6
REWARD_DEFAULT = -5
REWARD_HIT = -100
REWARD_DODGE = 10
REWARD_STILL = 2
REWARD_HEAL = 500

DEFAULT_LEARNING_RATE = 0.1
DEFAULT_DISCOUNT_FACTOR = 1

SPRITE_SIZE = 64
