STILL, LEFT, RIGHT = 'S', 'L', 'R'
ACTIONS = [RIGHT, LEFT, STILL]

REWARD_IMPOSSIBLE = -60
REWARD_STUCK = -6
REWARD_DEFAULT = -2
REWARD_HIT = -50
REWARD_DODGE = 10
REWARD_STILL = 2
REWARD_HEAL = 30

DEFAULT_LEARNING_RATE = 1
DEFAULT_DISCOUNT_FACTOR = 0.7

SPRITE_SIZE = 64
