STILL, LEFT, RIGHT = 'S', 'L', 'R'
ACTIONS = [RIGHT, LEFT, STILL]

REWARD_IMPOSSIBLE = -60
REWARD_STUCK = -1000
REWARD_DEFAULT = -5
REWARD_HIT = -500
REWARD_ALMOST_HIT = -100
REWARD_DODGE = 15
REWARD_STILL = 5
REWARD_HEAL = 500
REWARD_GOTO_HEAL = -7

DEFAULT_LEARNING_RATE = 0.1
DEFAULT_DISCOUNT_FACTOR = 0.5

SPRITE_SIZE = 64
